### ISSUE TITLE
Obtain frequency of channels

### ISSUE THREAD

**Issue by mkalte666** [martincameron/micromod#10]
Greetings, 

I found your project because, to learn a bit, i wanted to build a small .mod playing floppy drive machine. 
Micromod-c runs well on stm32! 

However because of the nature of floppy drives, i cannot use the sampled output but need the frequency. I kinda threw that into the lib in a fork - maybe you would like that in the lib, too! 

https://github.com/martincameron/micromod/compare/master...mkalte666:master

**Comment by martincameron** [comment]
Good to hear you've made use of it!

I'm trying to keep the C version as small as possible, so I'd rather
functions like these were kept out of the base library. Hope you don't
mind!

Thanks,
Martin

**Comment by mkalte666** [comment]
I see why you are suggesting this. Very well, that ill crawl back into the dark pit that is my weekend project idea blob ^^ 
Im just trying to help, and maybe someone needed that specific feature, so writing it down here was what came to mind. 

Keep up the good work!
