### ISSUE TITLE
[JS Library] Audio playback has sound issues when using the Browser Audio Worklet API

### ISSUE THREAD

**Issue by jamsinclair** [martincameron/micromod#19]
Firstly thanks for all the hard work and this neat library!

I've been playing around and testing the JS port with the [Audio Worklet API](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet). Due to the fact that the Script Processor API used in this project, and many other Audio projects, has been deprecated for some years now. 

The good news is that the library works with the Worklet API! As to be expected, there were some audio regressions. I've put this down to the buffer size on each `getAudio` call is considerably smaller at 128 samples. The Script Processsor fetches a buffer size of usually 4096 samples.

I've put together an example project comparing the two:
-  https://codesandbox.io/s/micromod-audio-worklet-example-6iyzp3

@martincameron I'm sure it's been a long time since you've been familiar with the code, but does anything come to mind where I should be investigating further with the JS code? Or what method is the likely culprit?

**Comment by martincameron** [comment]
The specs aren't very clear but here's what you have to do...

// One output, 2 channels(stereo)

Player.createNode() {
    return new AudioWorkletNode(this.context, PROCESSOR_MODULE_NAME, {
      numberOfInputs: 0,
      numberOfOutputs: 1,
      outputChannelCount: [2]
    });
}

ModProcessor.process(_inputs, outputs, _parameters) {
    if (
      outputs.length !== 1 ||
      !this.audioSource ||
      !this.module ||
      !this.isPlaying
    ) {
      return true;
    }

    const leftBuf = outputs[0][0];
    const rightBuf = outputs[0][1];
    const bufferSize = Math.min(leftBuf.length, rightBuf.length);
    this.audioSource.getAudio(leftBuf, rightBuf, bufferSize);

    return true;
  }

Hope this helps,
Cheers,
Martin

**Comment by jamsinclair** [comment]
@martincameron many thanks!

Silly me, I was conflating the outputs with channels. That's makes a lot of sense and fixes my issues. Cheers!
